version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postres
      POSTGRES_PASSWORD: user
    ports:
      - '5433:5433'
    expose:
      - '5433'
